apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: dotnet-react-dapr-2022-06-11t11-36-11
spec:
  encryptedData:
    .dockerconfigjson: AgCtKp0zAQKe3vdGP1jTnVFw9Fcj3QxNPqgYkxI2hqYxOZ05Xfxb1O9pxPlWWOvNNOVskvf4zpLJ6jLJsxsC9SW4+T/abdBS+zaUWOL0j4faVyp30nrDxD/tH+JvakULul0Vgn+wtt7mIA+5ots8FMBnWUIvbqp9n9Rr3QVzX4YnKrSS07B+24ZfSSGiB6jCT0aatPsK+hqUoPeN1kqPT/d5nzQhCd8pj6QGn4YH2LXY7WfmjHhLHwZ0VPrjYZQR7TXvzU63j7nX/asIoEEou8eltNpN8M/+L9oVgXR0+P/GodIHdQLRM4EL1Ri19K68gZac1qKfdfVkoK+It6WlErPUcqq+k3GMcA7p+YrMHMECRrP/7tWdd1gfDnxnvOtBEqZl2MriVzpfuuJNf8Yjs49b5eRBEziFvOAyPb1qP03mItqulK9GvylJy3nnb09y4QTLgqvl4fxM44HNYNL0ltcn/JFSKLTVFoesPq3hDVPxwiKGlFFWgGOIgZUv8LU4TgikVZPPJBW1gS1/67G5bmTHKuEY4eA5aeqojiiv660Slp4vZJvzmjapPEQZ96Y2OF36XNiqC1cPrn88NpnNumbzwKbh1YkdPWu5hPrfCyMTJLmZgtuvNFUdncLJhLdC6a6IUDVMGkJre9rVdxKKR63Ii/QZW9UpCvSfTZO0zCch7svmE7BlSs/cHzMf3z1W7wLLDS1s4VZZxbzHQmjrpbqugHht1i3ZYIHNXWCy9rN9s5xH0jCiVhPV6Yk6I0NzAQCGMcCy53v7qEo9ddxUSPjKDunI/PAH53OhFw8/Yfwl9g3JBPENp8qAIYnBUuE/Off98+rBMY1J1sJajaySZZRX/zJ92omjy9wvCV+6Vz4E8Ttgq9Hpgf2G4DOKuuD7+REtijZxhNRLUHZnK/TGujBGFkdnKCavO3qsRT4Nq+jULdDZR6+9wvDaLs4/o91HUT4=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: dotnet-react-dapr-2022-06-11t11-36-11
    type: kubernetes.io/dockerconfigjson

